AllCops:
  Excludes:
    - db/schema.rb
    - config/locales/devise.en.yml
    - db/migrate/*
    - config/routes.rb
    - config/environments/development.rb
    - app/controllers/users/omniauth_callbacks_controller.rb
    - app/controllers/accounts_controller.rb
    - app/models/user.rb
    - db/seeds/*
Style/Documentation:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericPredicate: 
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
